---
jobs:
- name: update-pipelines
  build_logs_to_retain: 3
  serial: true
  plan:
  - in_parallel:
    - get: pipeline-ecosystem
      trigger: true
    - get: builder

  - task: Update pipelines
    image: builder
    timeout: 20m
    privileged: true
    params:
      CONCOURSE_TARGET: bitglob
      CONCOURSE_URL: https://ci.bitcoin-global.dev/
      CONCOURSE_TEAM: main
      CONCOURSE_USERNAME: ((concourse.username))
      CONCOURSE_PASSWORD: ((concourse.password))
    config:
      platform: linux
      inputs:
        - name: pipeline-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - |
            ### Login
            fly --target $CONCOURSE_TARGET login \
               --concourse-url $CONCOURSE_URL --team-name $CONCOURSE_TEAM \
               --username ${CONCOURSE_USERNAME} --password ${CONCOURSE_PASSWORD}

            ### Run all pipeline scripts
            cd ./pipeline-ecosystem/pipelines
            for f in ./*.pipeline.sh; do
              bash "$f" -H
            done
  
  <: ((inject slack-notify))