---
jobs:
- name: make-builder
  serial: true
  plan:
  - get: builder-ecosystem
    trigger: true
  - put: builder
    params:
      build: builder-ecosystem/src/builder
      additional_tags: builder-ecosystem/src/builder/version
  <: ((inject slack-notify))