---
jobs:
- name: make-builder
  serial: true
  plan:
  - get: global-ecosystem
  - put: builder
    params:
      build: global-ecosystem/src/builder
      additional_tags: global-ecosystem/src/builder/version
  <: ((inject slack-notify))