---
jobs:
- name: make-builder
  serial: true
  plan:
  - get: bitcoin-infra
  - put: bitcoin-builder
    params:
      build: bitcoin-infra/src/builder
      additional_tags: bitcoin-infra/src/builder/version
