---
### Resource overrides
meta_plan:
  build-config: &build-config
    image: builder
    timeout: 4h
    privileged: true
    <: (( inject meta.release-params ))

  publish-config: &publish-config
    image: builder
    timeout: 10m
    privileged: true
    <: (( inject meta.release-params ))

  vm-control-config: &vm-control-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  boot-vm:
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_builder ))

  build-release:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.get_btg_version ))
    - (( grab meta.wait_for_builder ))
    - (( join "\n" meta.builder_release ))

  publish-release:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.get_btg_version ))
    - (( grab meta.wait_for_builder ))
    - (( join "\n" meta.builder_publish ))

  shutdown-vm:
    - (( grab meta.configure_gcloud ))
    - (( grab meta.builder_stop ))

### Pipeline config
jobs:

## Build step
- name: build
  build_logs_to_retain: 3
  serial: true
  plan:
  - in_parallel:
    - get: bitcoin-global
      passed: [deploy-builder]
      trigger: true
    - get: builder
      passed: [deploy-builder]
    - get: global-ecosystem
      passed: [deploy-builder]

  - task: Boot Build VM
    <<: *vm-control-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.boot-vm ))

  - task: Build release candidates
    <<: *build-config
    config:
      platform: linux
      inputs:
        - name: bitcoin-global
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.build-release ))

  # Whatever happens, make sure we have switched off the VM for cost reduction
  ensure: &shudown
    task: Shutdown Build VM
    <<: *vm-control-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.shutdown-vm ))

  <: ((inject slack-notify))


## Release step
- name: publish
  build_logs_to_retain: 3
  serial: true
  plan:
  - in_parallel:
    - get: bitcoin-global
      passed: [build]
    - get: builder
      passed: [build]
    - get: global-ecosystem
      passed: [build]

  - task: Boot Build VM
    <<: *vm-control-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.boot-vm ))

  - task: Publish releases
    <<: *publish-config
    config:
      platform: linux
      inputs:
        - name: bitcoin-global
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.publish-release ))

  # Whatever happens, make sure we have switched off the VM for cost reduction
  ensure: &shudown
    task: Shutdown Build VM
    <<: *vm-control-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.shutdown-vm ))

  <: ((inject slack-notify))
