---
meta:
  overrides:
    bitcoin-global:
      branch: "0.19.1-bootstrap"

  release-params: &release-params
    params:
      #========================================================
      # Service config
      SERVICE_ACCOUNT               : ((gcp.service-account-email))
      GCLOUD_CREDENTIALS            : ((gcp.service-account))
      GCP_PROJECT                   : bitcoin-global-infra
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud.json
      GITHUB_TOKEN                  : ((git.token))
      SSH_PRIVATE_KEY               : ((ssh.private))
      SSH_PUBLIC_KEY                : ((ssh.public))
      SSH_USER                      : ((ssh.username))
      GPG_SIGNER                    : ((gpg.signer))
      GPG_PUBLIC                    : ((gpg.public))
      GPG_PRIVATE                   : ((gpg.private))
      GPG_SUBKEY                    : ((gpg.subkey))
      RELEASE_CERT                  : ((cert.cert))
      RELEASE_KEY                   : ((cert.key))
      TERM                          : xterm-256color
      RELEASE_TYPE                  : wlm
      #========================================================
      # Monitoring
      NETDATA_INFRA_ROOM            : eac6a6d5-154c-4e40-9fec-d29da19fb962
      NETDATA_INFRA_TOKEN           : ((monitoring.infra-token))
      #========================================================
      # Builder config
      BUILDER_VM_NAME               : master-bitcoin-builder
      BUILDER_VM_ZONE               : europe-west2-b
      BUILDER_VM_SIZE               : n1-highcpu-8
      BUILDER_CPUS                  : 8
      BUILDER_RAM_MEMORY            : 6500
      BUILDER_DISK_SIZE             : 60GB
      BUILDER_DISK_TYPE             : pd-standard
      BUILDER_SCRIPT_PATH           : /tmp/builder-startup.sh
