---
meta:
  release-params: &release-params
    params:
      SERVICE_ACCOUNT               : ((gcp.service-account-email))
      GCLOUD_CREDENTIALS            : ((gcp.service-account))
      GCP_PROJECT                   : bitcoin-global-infra
      GKE_CLUSTER                   : eu-master-cluster
      GKE_CLUSTER_ZONE              : europe-west1-b
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud.json
      GITHUB_TOKEN                  : ((git.token))
      SSH_PRIVATE_KEY               : ((ssh.private))
      SSH_PUBLIC_KEY                : ((ssh.public))
      SSH_USER                      : ((ssh.username))
      GPG_SIGNER                    : ((gpg.signer))
      GPG_PUBLIC                    : ((gpg.public))
      GPG_PRIVATE                   : ((gpg.private))
      GPG_SUBKEY                    : ((gpg.subkey))
      RELEASE_CERT                  : ((cert.cert))
      RELEASE_KEY                   : ((cert.key))
      TERM                          : xterm-256color
      RELEASE_TYPE                  : wlm
      # Monitoring
      NETDATA_INFRA_ROOM            : eac6a6d5-154c-4e40-9fec-d29da19fb962
      NETDATA_INFRA_TOKEN           : ((monitoring.infra-token))
      # Builder config
      BUILDER_VM_NAME               : master-bitcoin-builder
      BUILDER_VM_ZONE               : us-central1-b
      BUILDER_VM_SIZE               : n1-highcpu-8
      BUILDER_DISK_SIZE             : 60GB
      BUILDER_DISK_TYPE             : pd-standard
      BUILDER_SCRIPT_PATH           : /tmp/builder-startup.sh
