---
meta:
  release-params: &release-params
    params:
      SERVICE_ACCOUNT               : ((gcp.service-account-email))
      GCLOUD_CREDENTIALS            : ((gcp.service-account))
      GCP_PROJECT                   : bitcoin-global-playground
      GKE_CLUSTER                   : eu-master-cluster
      GKE_CLUSTER_ZONE              : europe-west1-b
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud.json
      GITHUB_TOKEN                  : ((git.token))
      SSH_PRIVATE_KEY               : ((ssh.private))
      SSH_PUBLIC_KEY                : ((ssh.public))
      SSH_USER                      : ((ssh.username))
      GPG_KEY                       : ((gpg.private))
      GPG_PASSPHRASE                : ((gpg.passphrase))
      TERM                          : xterm-256color
      RELEASE_TYPE                  : wlm
      # Builder config
      BUILDER_VM_NAME               : master-bitcoin-builder
      BUILDER_VM_ZONE               : us-central1-b
      BUILDER_VM_SIZE               : n2-highcpu-16
      BUILDER_DISK_SIZE             : 100GB
      BUILDER_DISK_TYPE             : pd-ssd
      BUILDER_SCRIPT_PATH           : /tmp/builder-startup.sh
