---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  vm-control-config: &vm-control-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  provision-vm:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.get_btg_version ))
    - (( grab meta.make_builder ))
    - (( grab meta.wait_for_builder ))
    - (( join "\n" meta.setup_builder ))

  shutdown-vm:
    - (( grab meta.configure_gcloud ))
    - (( grab meta.builder_stop ))


### Pipeline config
jobs:
- name: deploy-builder
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: builder
    - get: global-ecosystem
    - get: bitcoin-global
      # trigger: true
    - get: global-electrum
      # trigger: true

  - task: Provision VM
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
        - name: bitcoin-global
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.provision-vm ))

  # Whatever happens, make sure we have switched off the VM for cost reduction
  ensure: &shudown
    task: Shutdown Build VM
    <<: *vm-control-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.shutdown-vm ))

  <: ((inject slack-notify))