---
### Resource overrides
meta_plan:
  discard-config: &discard-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  discard-vm:
    - (( grab meta.configure_gcloud ))
    - (( grab meta.builder_destroy ))

### Pipeline config
jobs:
- name: deprovision-build-vm
  build_logs_to_retain: 3
  serial: true
  plan:
  - in_parallel:
    - get: bitcoin-global
      passed: [build-releases]
      trigger: true
    - get: builder
      passed: [build-releases]
    - get: global-ecosystem
      passed: [build-releases]

  - task: Discard VM
    <<: *discard-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.discard-vm ))

  <: ((inject slack-notify))
