---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  provision-vm:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_builder ))
    - (( grab meta.wait_for_builder ))
    - (( join "\n" meta.builder_setup ))

### Pipeline config
jobs:
- name: provision-build-vm
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: bitcoin-infra
    - get: bitcoin-global
      trigger: true
    - get: builder

  - task: Provision VM
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: bitcoin-infra
        - name: bitcoin-global
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.provision-vm ))
