---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: bitcoin-builder
    privileged: true
    <: (( inject meta.builder-params ))

  provision-vm:
    - (( grab meta.configure_git ))
    - (( grab meta.export-gcloud-json ))
    - (( grab meta.export-startup-script ))
    - |
      # Deploy Builder VM on GCP
      chmod +x bitcoin-infra/scripts/add-vm.sh
      bitcoin-infra/scripts/add-vm.sh \
        --name="$BUILDER_VM_NAME" \
        --zone="$BUILDER_VM_ZONE" \
        --size="$BUILDER_VM_SIZE" \
        --disk-size="$BUILDER_DISK_SIZE" \
        --disk-type="$BUILDER_DISK_TYPE" \
        --script-path="$BUILDER_SCRIPT_PATH"

### Pipeline config
jobs:
- name: provision-build-vm
  build_logs_to_retain: 3
  serial: true
  plan:
  - in_parallel:
    - get: bitcoin-infra
    - get: bitcoin-builder

  - task: Provision VM
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: bitcoin-infra
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.provision-vm ))
