---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: builder
    timeout: 1h
    privileged: true
    <: (( inject meta.config-params ))

  provision-vm:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_nodeinfra ))
    - (( grab meta.wait_for_nodeinfra ))
    - (( join "\n" meta.setup_nodeinfra ))

  deploy-io:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_nodeinfra ))
    - (( grab meta.wait_for_nodeinfra ))
    - (( join "\n" meta.setup_io ))


jobs:
- name: deploy-dns-seeds
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: Provision Infra VM
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.provision-vm ))
  <: ((inject slack-notify))

- name: deploy-landing-page
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: global-io
      trigger: true
    - get: builder
    - get: global-ecosystem

  - task: Deploy landing page
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-io
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-io ))
  <: ((inject slack-notify))

