---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: builder
    timeout: 1h
    privileged: true
    <: (( inject meta.config-params ))

  mainnet-config: &mainnet-config
    image: builder
    timeout: 1h
    privileged: true
    <: (( inject meta.mainnet-params ))

  provision-vm:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_nodeinfra ))
    - (( grab meta.wait_for_nodeinfra ))
    - (( join "\n" meta.setup_nodeinfra ))

  deploy-io:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_nodeinfra ))
    - (( grab meta.wait_for_nodeinfra ))
    - (( join "\n" meta.setup_io ))

  check-ibd-status:
    - (( grab meta.configure_git ))
    - (( grab meta.servers_ssh ))
    - (( join "\n" meta.check_ibd ))

resources:
- name: timer-24h
  type: time
  icon: clock-outline
  source: {interval: 24h}

jobs:
- name: deploy-dns-seeds
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: Provision Infra VM
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.provision-vm ))
  <: ((inject slack-notify))

- name: deploy-landing-page
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: global-io
      trigger: true
    - get: builder
    - get: global-ecosystem

  - task: Deploy landing page
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-io
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-io ))
  <: ((inject slack-notify))

- name: mainnet-ibd
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: builder
    - get: timer-24h
      trigger: true

  - task: Mainnet IBD status
    <<: *mainnet-config
    config:
      platform: linux
      inputs: []
      params:
        SERVER_SSH_PRIVATE_KEY: ((ssh.hivemindf-private))
        SERVER_SSH_PUBLIC_KEY : ((ssh.hivemindf-public))
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.check-ibd-status ))
  <: ((inject slack-notify))

