---
### Resource overrides
meta_plan:
  provision-config: &provision-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.release-params ))

  deploy-node:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_node ))
    - (( grab meta.wait_for_node ))
    - (( join "\n" meta.setup_node ))

### Pipeline config
jobs:
- name: deploy-test-nodes
  build_logs_to_retain: 3
  serial: true
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: Provision node
    <<: *provision-config
    config:
      platform: linux
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-node ))

  <: ((inject slack-notify))