---
meta:
  config-params: &config-params
    params:
      SERVICE_ACCOUNT               : ((gcp.service-account-email))
      GCLOUD_CREDENTIALS            : ((gcp.service-account))
      GCP_PROJECT                   : bitcoin-global-infra
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud.json
      GITHUB_TOKEN                  : ((git.token))
      TERM                          : xterm-256color
