### Resource overrides
meta_plan:
  shared-config: &shared-config
    image: builder
    timeout: 20m
    privileged: true
    <: (( inject meta.config-params ))

  deploy-node:
    - (( grab meta.configure_git ))
    - (( grab meta.configure_gcloud ))
    - (( grab meta.make_node ))
    - (( grab meta.wait_for_node ))
    - (( join "\n" meta.setup_node ))

### Pipeline config
jobs:


- name: europe-west1-b-main
  build_logs_to_retain: 3
  <: ((inject slack-notify))
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: "Provision node [main-europe-west1-b]"
    <<: *shared-config
    config:
      platform: linux
      params: 
        # Node config
        NODE_NAME                     : europe-west1-b-main-global-node
        NODE_ZONE                     : europe-west1-b
        NODE_TYPE                     : main-net
        NODE_SIZE                     : n1-standard-1
        NODE_DISK_SIZE                : 400GB
        NODE_DISK_TYPE                : pd-standard
        BITCOIN_ENTRYPOINT            : -bootstrap -daemon
        # Monitoring
        NETDATA_INFRA_ROOM            : b99a57d2-397a-4d9d-9655-3113b1c8ccef
        NETDATA_INFRA_TOKEN           : ((monitoring.infra-token))
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-node ))



- name: europe-west1-b-test
  build_logs_to_retain: 3
  <: ((inject slack-notify))
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: "Provision node [test-europe-west1-b]"
    <<: *shared-config
    config:
      platform: linux
      params: 
        # Node config
        NODE_NAME                     : europe-west1-b-test-global-node
        NODE_ZONE                     : europe-west1-b
        NODE_TYPE                     : test-net
        NODE_SIZE                     : g1-small
        NODE_DISK_SIZE                : 60GB
        NODE_DISK_TYPE                : pd-standard
        BITCOIN_ENTRYPOINT            : -testnet -bootstrap -daemon
        # Monitoring
        NETDATA_INFRA_ROOM            : a9c21a87-65f9-4bd8-86b0-e9de831a597a
        NETDATA_INFRA_TOKEN           : ((monitoring.infra-token))
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-node ))

- name: us-central1-test
  build_logs_to_retain: 3
  <: ((inject slack-notify))
  plan:

  - in_parallel:
    - get: global-ecosystem
    - get: builder

  - task: "Provision node [test-us-central1]"
    <<: *shared-config
    config:
      platform: linux
      params: 
        # Node config
        NODE_NAME                     : us-central1-test-global-node
        NODE_ZONE                     : us-central1
        NODE_TYPE                     : test-net
        NODE_SIZE                     : g1-small
        NODE_DISK_SIZE                : 60GB
        NODE_DISK_TYPE                : pd-standard
        BITCOIN_ENTRYPOINT            : -testnet -bootstrap -daemon
        # Monitoring
        NETDATA_INFRA_ROOM            : a9c21a87-65f9-4bd8-86b0-e9de831a597a
        NETDATA_INFRA_TOKEN           : ((monitoring.infra-token))
      inputs:
        - name: global-ecosystem
      run:
        user: root
        path: bash
        args:
          - -exc
          - (( join "\n" meta_plan.deploy-node ))



### Group configs
groups:

- name: main-net
  jobs:
  
  - europe-west1-b-main
  

- name: test-net
  jobs:
  
  - europe-west1-b-test
  
  - us-central1-test
  

